name: Publish Docker image
on: 
  push:
      tags:
        - v*
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Extract repository name
        shell: bash
        run: echo "::set-output name=repository::${GITHUB_REPOSITORY}"
        id: extract_repository
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"
        id: extract_branch
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN_CONTAINER_PUSH }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.extract_repository.outputs.repository }}:latest
            ghcr.io/${{ steps.extract_repository.outputs.repository }}:${{ steps.extract_branch.outputs.branch }}
